name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update repos
        run: sudo apt-get update -y

      - name: Install OpenVPN, rsync and sshpass
        run: sudo apt-get install -y openvpn rsync sshpass

      - name: Setup VPN Config
        run: |
          # Make file from secrets
          echo "${{ secrets.VPN_CONFIG }}" > config.ovpn

      - name: Connect to VPN
        run: |
          sudo openvpn --config config.ovpn --daemon
          sleep 10
          # Test connection using local address
          ping -W 2 -c 4 2001:6d8:10:1127::6246 

      - name: Rsync with Password
        run: |
          sshpass -p "${{ secrets.UNIX_PASSWORD }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./public/ promat@web.agh.edu.pl:/public_html

      - name: Kill VPN
        if: always()
        run: sudo killall openvpn
