name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Setup VPN Config
        run: |
          # Make file from secrets
          echo "${{ secrets.VPN_CONFIG }}" > config.ovpn

      - name: Connect to VPN
        run: |
          sudo openvpn --config config.ovpn --daemon

          sleep 10
          #ping -c 4 10.x.x.x test connection

      - name: Kill VPN
        if: always()
        run: sudo killall openvpn
