name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update repos
        run: sudo apt-get update

      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      - name: Install sshfs
        run: sudo apt-get install -y sshfs

      - name: Setup VPN Config
        run: |
          # Make file from secrets
          echo "${{ secrets.VPN_CONFIG }}" > config.ovpn

      - name: Connect to VPN
        run: |
          sudo openvpn --config config.ovpn --daemon
          sleep 10
          
      - name: Connect to Server
        run: |
          mkdir server
          sshfs -o password_stdin ${{ vars.URL  }}:/public_html server/ <<< '${{ secrets.UNIX_PASSWORD }}'

      - name: Kill VPN
        if: always()
        run: sudo killall openvpn
